title: RA_1501_gérer_les_politiques_du_système_de_gestion_des_ordinateurs_distants
id: RA1501
description: >
  Make sure you can manage Remote Computer Management system policies
author: your name/nickname/twitter
creation_date: DD.MM.YYYY
stage: Préparation
automation:
  - thehive/phantom/demisto/etc
references:
  - https://example.com
workflow: |
  Description of the workflow for the Response Action in markdown format.  
  Here newlines will be saved.  
