title: RA_1006_Configurer_un_stockage_centralisé_des_journaux_à_long_terme
id: RA1006
description: >
  Set up a centralized long-term log storage. This is one of the most critical problems companies have nowadays. Even if there is such a system, in most of the cases it stores irrelevant data or has too small retention period
author: your name/nickname/twitter
creation_date: DD.MM.YYYY
stage: Préparation
automation:
  - thehive/phantom/demisto/etc
references:
  - https://example.com
workflow: |
  Description of the workflow for the Response Action in markdown format.  
  Here newlines will be saved.  
