title: RA_2103_liste_des_hôtes_qui_ont_communiqués_avec_une_URL_interne
id: RA2103
description: >
  List hosts communicated with an internal URL
author: name/nickname/twitter
creation_date: DD.MM.YYYY
stage: identification
automation:
  - thehive
references:
  - https://example.com
workflow: |
  Description of the workflow for the Response Action in markdown format.  
  Here newlines will be saved.
