title: RA_2109_liste_des_hôtes_connectés_à_l'intranet
id: RA2109
description: >
  List hosts connected to the internal network at the moment or at a particular time in the past
author: your name/nickname/twitter
creation_date: DD.MM.YYYY
stage: identification
automation:
  - thehive/phantom/demisto/etc
references:
  - https://example.com
workflow: |
  Description of the workflow for the Response Action in markdown format.  
  Here newlines will be saved.  
