title: RA_2205_extraire_les_observables_du_message_électronique
id: RA2205
description: Extract observables from an email message
author: '@atc_project'
creation_date: 31.01.2019
stage: identification
automation:
  - thehive
references: 
  - https://ubuntuincident.wordpress.com/2010/09/27/extract-email-attachments/
  - https://blog.thehive-project.org/2018/07/31/emlparser-a-new-cortex-analyzer-for-eml-files/
workflow: |
  Extract the data for further response steps:  

  - attachments (using munpack tool: `munpack email.eml`)  
  - from, to, cc  
  - subject of the email  
  - received servers path  
  - list of URLs from the text content of the mail body and attachments  

  This Response Action could be automated with [TheHive EmlParser](https://blog.thehive-project.org/2018/07/31/emlparser-a-new-cortex-analyzer-for-eml-files/).  
