title: RA_2105_analyser l'IP
id: RA2105
description: >
  Analyse an IP address
author: name/nickname/twitter
creation_date: DD.MM.YYYY
stage: identification
automation:
  - thehive
references:
  - https://example.com
workflow: |
  Description of the workflow for the Response Action in markdown format.  
  Here newlines will be saved.  
