title: RA_2001_répertorier_les_victimes_de_l'alerte_de_sécurité
id: RA2001
description: >
  List victims of a security alert
author: name/nickname/twitter
creation_date: DD.MM.YYYY
stage: Identification
automation:
  - thehive
references: 
  - https://example.com
workflow: |
  Description of the workflow for the Response Action in markdown format.  
  Here newlines will be saved.  
