title: RA_2102_liste_des_hôtes_qui_ont_communiqués_avec_l'IP_interne
id: RA2102
description: >
  List hosts communicated with an internal IP address
author: name/nickname/twitter
creation_date: DD.MM.YYYY
stage: identification
automation:
  - thehive
references: 
  - https://example.com
workflow: |
  Description of the workflow for the Response Action in markdown format.  
  Here newlines will be saved.
