title: RA_2601_répertorier_les_utilisateurs_authentifiés
id: RA2601
description: >
  List users authenticated at a particular time in the past on a particular system
author: name/nickname/twitter
creation_date: DD.MM.YYYY
stage: identification
automation:
  - thehive
references:
  - https://example.com
workflow: |
  Description of the workflow for the Response Action in markdown format.  
  Here newlines will be saved.
