title: RA_2106_analyser_l'URI
id: RA2106
description: >
  Analyse an URI
author: name/nickname/twitter
creation_date: DD.MM.YYYY
stage: Identification
automation:
  - thehive
references: 
  - https://example.com
workflow: |
  Description of the workflow for the Response Action in markdown format.  
  Here newlines will be saved.  
