title: RA_3001_Corriger_la_vulnérabilité
id: RA3001
description: >
  Patch a vulnerability in an asset
author: name/nickname/twitter
creation_date: DD.MM.YYYY
stage: containment
automation:
  - thehive
references:
  - https://example.com
workflow: |
  Description of the workflow for the Response Action in markdown format.  
  Here newlines will be saved.
