title: RA_4301_effacer_le_fichier
id: RA4301
description: >
  Remove a specific file from a (remote) host or a system
author: your name/nickname/twitter
creation_date: DD.MM.YYYY
stage: eradication
automation:
  - thehive/phantom/demisto/etc
references:
  - https://example.com
workflow: |
  Description of the workflow for the Response Action in markdown format.  
  Here newlines will be saved.  
