title: RA_5001_réinstaller_l'hôte_à_partir_d'une_image_propre
id: RA5001
description: >
  Reinstall host OS from a golden image
author: name/nickname/twitter
creation_date: DD.MM.YYYY
stage: Recouvrement
automation:
  - thehive
references: 
  - https://example.com
workflow: |
  Description of the workflow for the Response Action in markdown format.  
  Here newlines will be saved.  
